### PR TITLE
ZD-278: Remove dependency on views_php contrib.

### PR DESCRIPTION
**Pull request by jeremylichtman**

### CODE REVIEW

**Comment by libkuman** [comment]
Hi Jeremy,

    Thanks for the pull request! Your changes look clean and well done.  As far as the changes to the views that were using views_php, did you just make those locally, or did you change them in the code as well? If you haven't changed them in code is there a chance you could share the exports of the views and i'll update code? I could also try to mimic your changes and use your new handlers.

Thanks again,
Mark Libkuman
Openflows

**Comment by jeremylichtman** [comment]
Hi Mark,

The changes to the views are in code, and are part of this PR. You may have to click to open the file in the code tab, as it is a large diff.

Regards,

Jeremy

**Comment by libkuman** [comment]
Hi Jeremy,

    Indeed, I did not notice the large diff that was hidden. Thanks for all this, i'll accept this pull request and then roll out a new release. 

Thanks again,
Mark Libkuman
Openflows

**Comment by jeremylichtman** [comment]
Thanks Mark.

**Pull request merged**
